[package]
name = "quickjs-sys"
version = "0.1.0"
authors = ["seu <seu@panopticon.re>"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen = "0.50"
